ranktracker/protected/modules/bum/controllers/InstallController.php
<?php
/**
 * InstallController class file.
 * Controller class file for installing this module.
 *
 * @copyright	Copyright &copy; 2012 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 */
/**
 * InstallController class.
 * @package		bum
 */

class InstallController extends BumController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/bum';
    
    
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // 
				'actions'=>array('index', 'MySQL', 'PostgreSQL', 'InstallRights', 'InstallDefaultUser', 'MySQL_scripts', 'PostgreSQL_scripts', 'howTo'),
				'expression'=>'Yii::app()->getModule("bum")->install',
			),
			array('allow',  // 
				'actions'=>array('upgrade'),
				'expression'=>'Yii::app()->getModule("bum")->install',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
    
    /**
     * About BUM.
     */
	public function actionIndex()
	{
		if ($this->module->install === true) {
            $this->render('install_notices');
        }else{
        }
	}
    
    /**
     * Usefull things.
     */
	public function actionHowTo()
	{
		if ($this->module->install === true) {
            $this->render('howTo');
        }else{
        }
	}

    /**
     * MySQL script file..
     */
	public function actionMySQL_scripts()
	{
		if ($this->module->install === true) {
            $this->render('MySQL_scripts');
        }else{
        }
	}
    
    /**
     * How to install BUM with MySQL database server..
     */
	public function actionMySQL()
	{
		if ($this->module->install === true) {
            $this->render('install_MySQL');
        }else{
        }
	}

    /**
     * MySQL script file..
     */
	public function actionPostgreSQL_scripts()
	{
		if ($this->module->install === true) {
            $this->render('PostgreSQL_scripts');
        }else{
        }
	}

    /**
     * How to install BUM with PosgreSQL database server..
     */
	public function actionPostgreSQL()
	{
		if ($this->module->install === true) {
            $this->render('install_PostgreSQL');
        }else{
        }
	}

	public function actionInstallRights()
	{
		if ($this->module->install) {
            $connection = Yii::app()->db;
            $transaction=$connection->beginTransaction();
            $rights = array();
            try {
                $auth = Yii::app()->authManager;
                if(get_class($auth) == "CPhpAuthManager"){
                    throw new CException('Please configure authManager to user CDbAuthManager; see instalation notes!');
                }
                
                $roleTree = array();
                $taskTree = array();
                $operationTree = array();
                
                if(!$auth->getAuthItem('users_admin')){
                    $operation = $auth->createOperation('users_admin', 'View all users + options.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('users_create')){
                    $operation = $auth->createOperation('users_create', 'Create a user.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('users_delete')){
                    $operation = $auth->createOperation('users_delete', 'Delete a user.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('users_all_view')){
                    $operation = $auth->createOperation('users_all_view', 'View all users.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('users_profile_update')){
                    $operation = $auth->createOperation('users_profile_update', 'Update a user profile.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('users_all_privateProfile_view')){
                    $operation = $auth->createOperation('users_all_privateProfile_view', 'View a user private profile.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('users_all_invites_view')){
                    $operation = $auth->createOperation('users_all_invites_view', 'View details about invites sent.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('password_change')){
                    $operation = $auth->createOperation('password_change', 'With this right user can change the password without knowing the old password.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }

                if(!$auth->getAuthItem('users_manage')){
                    $task = $auth->createTask('users_manage', 'Manage users!');
                }else{
                     $task = $auth->getAuthItem('users_manage');
                }
                if(!$task->hasChild('users_admin')) $task->addChild('users_admin');
                if(!$task->hasChild('users_create')) $task->addChild('users_create');
                if(!$task->hasChild('users_delete')) $task->addChild('users_delete');
                if(!$task->hasChild('users_all_view')) $task->addChild('users_all_view');
                if(!$task->hasChild('users_profile_update')) $task->addChild('users_profile_update');
                if(!$task->hasChild('users_all_privateProfile_view')) $task->addChild('users_all_privateProfile_view');
                if(!$task->hasChild('users_all_invites_view')) $task->addChild('users_all_invites_view');
                if(!$task->hasChild('password_change')) $task->addChild('password_change');
                
                $taskTree[] = array(
                        'text' => "<B>{$task->name}</B> task <I>{$task->description}</I>", 
                        'hasChildren' => true,
                        'children' => $operationTree);

                $operationTree = array();
                
                if(!$auth->getAuthItem('emails_create')){
                    $operation = $auth->createOperation('emails_create', 'Create a secondary email.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('emails_verificationLink_resend')){
                    $operation = $auth->createOperation('emails_verificationLink_resend', 'Resend the verification link.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('emails_delete')){
                    $operation = $auth->createOperation('emails_delete', 'Delete a secondary email.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                if(!$auth->getAuthItem('emails_all_view')){
                    $operation = $auth->createOperation('emails_all_view', 'View all emais.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }

                if(!$auth->getAuthItem('emails_manage')){
                    $task = $auth->createTask('emails_manage', 'Manage secondary emails!');
                }else{
                     $task = $auth->getAuthItem('emails_manage');
                }
                if(!$task->hasChild('emails_create')) $task->addChild('emails_create');
                if(!$task->hasChild('emails_verificationLink_resend')) $task->addChild('emails_verificationLink_resend');
                if(!$task->hasChild('emails_delete')) $task->addChild('emails_delete');
                if(!$task->hasChild('emails_all_view')) $task->addChild('emails_all_view');

                $taskTree[] = array(
                        'text' => "<B>{$task->name}</B> task <I>{$task->description}</I>", 
                        'hasChildren' => true,
                        'children' => $operationTree);
                        
                $operationTree = array();

                if(!$auth->getAuthItem('settings_emails_customization')){
                    $operation = $auth->createOperation('settings_emails_customization', 'Allow user to customize emais sent by this application.');
                        $operationTree[] = array('text'=>"<B>{$operation->name}</B> operation <I>{$operation->description}</I>");
                }
                
                if(!$auth->getAuthItem('settings_manage')){
                    $task = $auth->createTask('settings_manage', 'Allow the user to change the default settings.');
                }else{
                     $task = $auth->getAuthItem('settings_manage');
                }

ranktracker/protected/modules/bum/controllers/InvitationsController.php
<?php
/**
 * InvitationsController class file.
 * Controller class file for table invitations.
 *
 * @copyright	Copyright &copy; 2012 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 */
/**
 * InvitationsController class.
 * @package		bum
 */

class InvitationsController extends BumController
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='/layouts/bum';

    /**
     * @var type Users; keeps the user that makes the invitation
     */
    private $_user = null;
    
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
            'userContext + AJAXCreate', // check to ensure valid user context
            'ajaxOnly + AJAXCreate, AJAXView', // allow only AJAX request
		);
	}

    /**
     * Protected method to load the associated Users model class
     * @param type $id_user
     * @throws CHttpException
     */
    protected function loadUser($id_user) {
        //if the user property is null, create it based on input id
        if($this->_user===null) {
            $this->_user = Users::model()->findbyPk($id_user);
            if($this->_user===null) {
                throw new CHttpException(404,'There is no user to place the invitation.');
            }
        }
        return $this->_user;
    }
    
    /**
     * Find the user that placed the request.
     * @param type $filterChain
     */
    public function filterUserContext($filterChain)
    {
        //set the user identifier based on either the GET or POST input
        //request variables
        $id_user = null;
        if(isset($_GET['id_user'])){
            $id_user = $_GET['id_user'];
        }elseif(isset($_POST['Invitations']['id_user'])){
            $id_user = $_POST['Invitations']['id_user'];
        }
        
        $this->loadUser($id_user);
        //complete the running of other filters and execute the requested action
        $filterChain->run();
    }
    
	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'AJAXCreate' and 'AJAXView' actions
				'actions'=>array('AJAXCreate', 'AJAXView', 'view'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
    
    /**
     * View intives sent, who sent them and who accepted..
     */
    public function actionView(){
        $model = new Invitations('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Invitations']))
            $model->attributes=$_GET['Invitations'];

        $this->render('view',array(
            'model'=>$model,
        ));
    }
    
    /**
	 * Creates a new model.
	 */
	public function actionAJAXCreate($processOutput = false){
        if (Yii::app()->request->isAjaxRequest) {
            $processOutput = true;
            Yii::app()->clientScript->scriptMap['jquery.js'] = false;
            // some jquery.yii scripts are still included several times; no observable problem, but still...
        }
        $model=new Invitations;
        $model->scenario = 'create';
        $model->id_user = $this->_user->id;
        
		$UsersData=UsersData::model()->findByPk($model->id_user);
        
        if($UsersData->invitations_left < 0 || $UsersData->invitations_left > 0){
            // Uncomment the following line if AJAX validation is needed
            $this->performAjaxValidation($model);

            if(isset($_POST['Invitations']))
            {
                $model->attributes=$_POST['Invitations'];
                $model->invitation_code = rand(1000, 9999);

        
                if($model->save()){
                    
                    $message = $this->sendInvitationEmail($model);
                    if(Yii::app()->mail->send($message)){
                        if($UsersData->invitations_left>0){
                            $UsersData->invitations_left--;
                            $UsersData->save();
                        }

                        echo json_encode(array('message'=>'Invitation sent!', 'status'=>'ok'));
                    }else{
                        // something went wrong...
                        echo json_encode(array('message'=>'Invitation could not be sent!', 'status'=>'not ok'));
                    }
                    
                }else{
                    $error = CActiveForm::validate($model);
                    if($error!='[]')
                        echo $error;
                }
            }else{
                $this->renderPartial('_AjaxForm', array('model'=>$model), false, $processOutput);
            }
        }else{
            Yii::app()->user->setFlash('notice', "No invitations left!");
            $this->renderPartial('_noInvitations', array('model'=>$model), false, $processOutput);
        }
	}

    /**
     * Send the invitation email. 
     * Uses Yii-Mail extension.
     * 
     * @param type $Emails
     * @return \YiiMailMessage
     */
    public function sendInvitationEmail($model){
        $moduleSiteEmailsContact = SiteEmailsContent::model()->findByAttributes(array("name" => 'sender_invitation'));
        
        $message = new YiiMailMessage;
        
        $message->view = 'invitation';
        $message->setBody(array('model'=>$model, 'moduleSiteEmailsContact' => $moduleSiteEmailsContact), 'text/html');
        $message->subject = $moduleSiteEmailsContact->subject;
        $message->addTo($model->email);
        $message->from = $this->module->sender_invitation;
        
        return $message;
    }
    
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionAJAXView($id_user, $processOutput = false){
        if (Yii::app()->request->isAjaxRequest) {
            $processOutput = true;
            Yii::app()->clientScript->scriptMap['jquery.js'] = false;
            // some jquery.yii scripts are still included several times; no observable problem, but still...
        }
        $dataProvider=new CActiveDataProvider('Invitations', array(
            'criteria'=>array(
                'condition'=>"id_user={$id_user}",
                'order'=>'date_of_invitation_send DESC',
            ),
            'pagination'=>array(
                'pageSize'=>5,
            ),
        ));
        
        $this->renderPartial('_AJAXView', array('dataProvider'=>$dataProvider), false, $processOutput);
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Invitations::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='invitations-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

ranktracker/protected/modules/bum/views/invitations/_AJAXView.php
<?php
/**
 * Show to whom invitation email has been sent; partial view.
 *
 * @copyright	Copyright &copy; 2012 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 * 
 * This form file is used to print email and status for invitations sent
 */

/* @var $this InvitationController */
/* @var $dataProvider Invitations -> for curent user */

?><H6>Invitations sent to:</H6>
<DIV style="height:150px; border-bottom:1px solid; border-color:#999; margin-bottom:5px; padding-bottom:5px; position: relative;"><?php $this->widget('zii.widgets.CListView', array(
    'id'=>'invitationsSentList',
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
    'htmlOptions'=>array('class'=>'container', 'style'=>'width:auto; position: absolute; bottom: 10px;'),
    'summaryText'=>'',
    'pagerCssClass'=>'left',
)); ?></DIV>

ranktracker/protected/modules/bum/views/invitations/_AjaxForm.php
<?php
/**
 * Send invitations; partial view.
 *
 * @copyright	Copyright &copy; 2012 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 * 
 * This form file is used to send invitations to friends.
 */

/* @var $this InvitationsController */
/* @var $model Invitations */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'invitations-form',
	'enableAjaxValidation'=>true,
    'htmlOptions'=>array('onSubmit'=>'return false;'), // deactivate the default submit action
    'enableClientValidation'=>true,
)); ?>
	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>
	<fieldset>

        <?php echo $form->hiddenField($model, 'id_user'); ?>
        <div class="row">
            <?php echo $form->labelEx($model,'email'); ?>
            <?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>60)); ?>
            <?php echo $form->error($model,'email'); ?>
        </div>

        <div class="row">
            <?php echo $form->labelEx($model,'note'); ?>
            <?php echo $form->textArea($model,'note',array('rows'=>6, 'cols'=>50)); ?>
            <?php echo $form->error($model,'note'); ?>
        </div>
        
	</fieldset>

<?php $this->endWidget(); ?>

</div><!-- form -->

ranktracker/protected/modules/bum/views/invitations/_noInvitations.php
<?php
/**
 * Print a flash message; partial view.
 *
 * @copyright	Copyright &copy; 2012 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 * 
 * This form file is used to print the "No invitations left" flash message...
 */

/* @var $this InvitationController */
/* @var $model Invitations */

foreach(Yii::app()->user->getFlashes() as $key => $message) {
    echo '<div class="flash-' . $key . '">' . $message . "</div>\n";
} 

ranktracker/protected/modules/bum/views/invitations/_search.php
<?php
/**
 * Search form for searching a user; partial view.
 *
 * @copyright	Copyright &copy; 2013 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 */

/* @var $this UsersController */
/* @var $model Users */
/* @var $form CActiveForm */

?><div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'search_user'); ?>
		<?php echo $form->textField($model,'search_user'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'search_user_invited'); ?>
		<?php echo $form->textField($model,'search_user_invited'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>60,'maxlength'=>60)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date_of_invitation_send'); ?>
		<?php echo $form->textField($model,'date_of_invitation_send',array('size'=>60,'maxlength'=>60)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date_of_invitation_accepted'); ?>
		<?php echo $form->textField($model,'date_of_invitation_accepted',array('size'=>60,'maxlength'=>60)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

ranktracker/protected/modules/bum/views/invitations/_view.php
<?php
/**
 * Print the invited emails and status..
 *
 * @copyright	Copyright &copy; 2012 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 * 
 * This form file is used to print email and status for invitations sent.
 */

/* @var $data Invitations -> dataprovider for curent user */

?><DIV class="column span-10 small bottom "><?php echo $data->email; ?></DIV>
<DIV class="span-5 last small bottom "><?php echo isset($data->date_of_invitation_accepted)?"Accepted":""; ?></DIV>

ranktracker/protected/modules/bum/views/invitations/view.php
<?php
/**
 * Manage all users view file.
 *
 * @copyright	Copyright &copy; 2013 Hardalau Claudiu 
 * @package		bum
 * @license		New BSD License 
 *  
 * Menu links are displayed only if the user has the right to see those pages.
 */

/* @var $this UsersController */
/* @var $model Users */

$this->breadcrumbs=array(
	'Invitations',
);

$cs = Yii::app()->getClientScript();
$cs->registerScriptFile(Yii::app()->getModule("bum")->assetsUrl . '/js/invitations.js');

$this->menu=array(
	array('label'=>'Install', 'url'=>array('install/index'), 'visible'=>(Yii::app()->getModule("bum")->install)),
	array('template'=>'<HR style="margin:0 auto;"/>', 'visible'=>(Yii::app()->getModule("bum")->install)), // separator
    
	array('label'=>'Settings', 'url'=>array('settings/batchUpdate'), 'visible'=>(Yii::app()->user->checkAccess("settings_manage"))),
	array('template'=>'<HR style="margin:0 auto;"/>', 'visible'=>(Yii::app()->user->checkAccess("settings_manage"))), // separator
    
	array('label'=>'My Profile (' . Yii::app()->user->name . ')', 'url'=>array('users/viewMyPrivateProfile', 'id'=>Yii::app()->user->id), 'visible'=>(Yii::app()->user->checkAccess("users_manage") && (!isset($model) || Yii::app()->user->id != $model->id))),
    
	array('template'=>'<HR style="margin:0 auto;"/>'), // separator
    
	array('label'=>'invite', 'url'=>'#', 
        'linkOptions'=>array(
                'onclick'=>'invitationDialog(
                        "' . Yii::app()->createUrl(Yii::app()->getModule("bum")->name . "/invitations/AJAXCreate", array('id_user'=>Yii::app()->user->id)) . '",
                        "' . Yii::app()->createUrl(Yii::app()->getModule("bum")->name . "/invitations/AJAXView", array('id_user'=>Yii::app()->user->id)) . '"
                    );' 
            ), 
        'visible'=>(!Yii::app()->user->isGuest && Yii::app()->getModule('bum')->invitationButtonDisplay)),
	array('template'=>'<HR style="margin:0 auto;"/>', 'visible'=>(!Yii::app()->user->isGuest && Yii::app()->getModule('bum')->invitationButtonDisplay)), // separator
    
	array('label'=>'Manage Users', 'url'=>array('users/admin'), 'visible'=>Yii::app()->user->checkAccess("users_admin")),
	array('label'=>'Create User', 'url'=>array('users/create'), 'visible'=>Yii::app()->user->checkAccess("users_create")),
	array('label'=>'View all Users', 'url'=>array('users/viewAllUsers'), 'visible'=>Yii::app()->user->checkAccess("users_all_view"), 'active'=>true),
    
	array('template'=>'<HR style="margin:0 auto;"/>', 'visible'=>(Yii::app()->user->checkAccess('users_all_privateProfile_view') && !Yii::app()->user->isGuest)), // separator
	array('label'=>'See Sent Invites', 'url'=>array('invitations/view'), 'visible'=>(Yii::app()->user->checkAccess('users_all_privateProfile_view') && !Yii::app()->user->isGuest)),
    
	array('template'=>'<HR style="margin:0 auto;"/>', 'visible'=>(Yii::app()->getModule("bum")->logInIfNotVerified && !Yii::app()->user->active && !Yii::app()->user->isGuest)), // separator
	array('label'=>'Resend Confirm. Email', 'url'=>array('users/resendSignUpConfirmationEmail'), 'visible'=>(Yii::app()->getModule("bum")->logInIfNotVerified && !Yii::app()->user->active && !Yii::app()->user->isGuest)),
);

/* Send an invitation dialog box */
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
    'id'=>'Invite',
    'options'=>array(
        'autoOpen'=>false,
        'modal'=>true,
    )
));
    ?><DIV id="dlg_history_content"></DIV><?php
    ?><DIV id="dlg_invite_content"></DIV><?php
    ?><div id="AjaxLoader" style="display: none; margin: 0 auto; text-align: center;"><IMG src="<?php echo Yii::app()->getModule("bum")->assetsUrl; ?>/images/spinner.gif" width="60px" height="60px" /></div><?php
$this->endWidget('zii.widgets.jui.CJuiDialog');

?>

<h1>See Invitations Sent</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p><?php 

Yii::app()->clientScript->registerScript('search', "
    $('.search-button').click(function(){
        $('.search-form').toggle();
        return false;
    });
    $('.search-form form').submit(function(){
        $.fn.yiiGridView.update('invitations-grid', {
            data: $(this).serialize()
        });
        return false;
    });
");
echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); 
?><div class="search-form" style="display:none"><?php 
$this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form --><?php 

$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'invitations-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
    //'afterAjaxUpdate' => 'function(){}',
	'columns'=>array(
		array(
            'name'=>'search_user',
            'value'=>'isset($data->idUser->user_name)?$data->idUser->user_name:""',
        ), // what user sent the invitation
		array(
            'name'=>'search_user_invited',
            'value'=>'isset($data->idUserInvited->user_name)?$data->idUserInvited->user_name:""',
        ), // what user accepted the invitation
		'email', // to what email was the invitation sent
        'note', // invitation note
        'date_of_invitation_send', // date when the invitation was sent
        'date_of_invitation_accepted', // date when the invitation was accepted
	),
)); 